### ISSUE TITLE
Frends.FixedWidthFlatFile.ConvertToXML

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.FixedWidthFlatFile#3]
Based on https://github.com/CommunityHiQ/Frends.Community.FixedWidthFlatFile, initial Parse task should be done already, so it is the same, but instead of an object - convert to XML

**Comment by helvertti** [comment]
Task implemented with latest instructions.

**Comment by helvertti** [comment]
Wrong issue closed - was meant to ConvertToJSON.

**Comment by helvertti** [comment]
Task implemented by latest instructions.
